### ISSUE TITLE
 default-requeue-rejected ignored

### ISSUE THREAD

**Issue by antoba** [freenowtech/spring-multirabbit#91]
if I'm not wrong the followring setting is completely ignored...  

```
      my-rabbitmq-connection:
        host: localhost
        port: 5672
        username: guest
        password: guest
        listener:
          simple:
            default-requeue-rejected:
```
